"""empty message

Revision ID: 8267e0dca6ea
Revises: b31879930b43
Create Date: 2020-07-11 23:04:10.937852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8267e0dca6ea'
down_revision = 'b31879930b43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('path', sa.String(length=150), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.Integer(), nullable=True),
    sa.Column('lft', sa.Integer(), nullable=False),
    sa.Column('rgt', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('tree_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['menu.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_name'), 'menu', ['name'], unique=False)
    op.create_index(op.f('ix_menu_path'), 'menu', ['path'], unique=False)
    op.create_index('menu_level_idx', 'menu', ['level'], unique=False)
    op.create_index('menu_lft_idx', 'menu', ['lft'], unique=False)
    op.create_index('menu_rgt_idx', 'menu', ['rgt'], unique=False)
    op.create_table('rel_group_menu',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('menu_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['menu_id'], ['menu.id'], ),
    sa.PrimaryKeyConstraint('id', 'group_id', 'menu_id')
    )
    op.create_index(op.f('ix_blacklist_token_token'), 'blacklist_token', ['token'], unique=False)
    op.alter_column('group', 'screen_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
    op.drop_index('ix_group_screen_name', table_name='group')
    op.alter_column('permission', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_index('ix_permission_description', table_name='permission')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_permission_description', 'permission', ['description'], unique=False)
    op.alter_column('permission', 'description',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_index('ix_group_screen_name', 'group', ['screen_name'], unique=False)
    op.alter_column('group', 'screen_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
    op.drop_index(op.f('ix_blacklist_token_token'), table_name='blacklist_token')
    op.drop_table('rel_group_menu')
    op.drop_index('menu_rgt_idx', table_name='menu')
    op.drop_index('menu_lft_idx', table_name='menu')
    op.drop_index('menu_level_idx', table_name='menu')
    op.drop_index(op.f('ix_menu_path'), table_name='menu')
    op.drop_index(op.f('ix_menu_name'), table_name='menu')
    op.drop_table('menu')
    # ### end Alembic commands ###
