"""empty message

Revision ID: 845239d0bafd
Revises: 8267e0dca6ea
Create Date: 2020-07-23 09:52:10.052121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '845239d0bafd'
down_revision = '8267e0dca6ea'
branch_labels = None
depends_on = None


def upgrade():
    op.create_index(op.f('ix_user_status'), 'user', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_status'), table_name='user')
    op.drop_index(op.f('ix_menu_path'), table_name='menu')
    op.drop_column('group', 'description')
    # ### end Alembic commands ###
